### PR TITLE
Fixed multiple file buffer bug.

### PR DESCRIPTION
**Pull request by Bill77**
Once opts.filename is set, all other files will use that same name. So the same file gets overwritten, but in order to support multiple .json files, had to add a temp variable that read the options object.

Also refactored the testing to support multiple files.

Relates to [Issue 6](https://github.com/mrooding/gulp-protractor-cucumber-html-report/issues/6).

### CODE REVIEW

**Comment by nmeierpolys** [comment]
I ran into the same issue. I just tested this commit with the fix locally and everything worked great.

**Comment by Bill77** [comment]
Hi @mrooding,

Is there any updates on this? We would like to incorporated these changes into our system.

Thanks in advance,
Bill

**Comment by mrooding** [comment]
@Bill77 Hi Bill, apologies for the silence. I'll come back to this this weekend once I've had the time to properly test this

**Comment by Bill77** [comment]
@mrooding Hi Marc, thanks for getting back to me, sure no problem, let me know if I can be of any help for your testing. :)

**Comment by Bill77** [comment]
@mrooding Hi Marc, was hoping for an update, thanks. :)

**Comment by mrooding** [comment]
Hi Bill, it took me a bit longer than expected but I've just merged this PR and released version 0.1.0

Let me know if you run into any issues and thanks for contributing!

**Comment by Bill77** [comment]
@mrooding, Awesome, was able to pull the NPM package today. Thanks for the help, sorry I was a nag in trying to get this release. But this helps our me to close out a branch for our team. :)

Appreciate the help!

**Pull request merged**
